[project]
name = "moci-ddasoop-file-be"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.1",
    "gunicorn>=23.0.0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
